{
 "title": "Corsair PSU",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(node_hwmon_power_watt,job)"
    }
   },
   {
    "name": "chip",
    "query": {
     "query": "label_values(node_hwmon_power_watt{job=~\"$job\"},chip)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "node_hwmon_power_watt{job=~\"$job\",chip=~\"$chip\"}\n  * on(job,instance,chip,sensor) group_left(label)\nnode_hwmon_sensor_label{job=~\"$job\",chip=~\"$chip\"}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "node_hwmon_curr_amps{job=~\"$job\",chip=~\"$chip\"}\n  * on(job,instance,chip,sensor) group_left(label)\nnode_hwmon_sensor_label{job=~\"$job\",chip=~\"$chip\"}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "node_hwmon_in_volts{job=~\"$job\",chip=~\"$chip\"}\n  * on(job,instance,chip,sensor) group_left(label)\nnode_hwmon_sensor_label{job=~\"$job\",chip=~\"$chip\"}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{job=~\"$job\",chip=~\"$chip\"}\n  * on(job,instance,chip,sensor) group_left(label)\nnode_hwmon_sensor_label{job=~\"$job\",chip=~\"$chip\"}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Fan",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "expr": "node_hwmon_fan_rpm{job=~\"$job\",chip=~\"$chip\"}\n  * on(job,instance,chip,sensor) group_left(label)\nnode_hwmon_sensor_label{job=~\"$job\",chip=~\"$chip\"}",
     "legendFormat": "{{label}}"
    }
   ]
  }
 ]
}