{
 "title": "llama.cpp",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(llamacpp_tokens_predicted_total,job)"
    }
   },
   {
    "name": "model",
    "query": {
     "query": "label_values(llamacpp_tokens_predicted_total{job=~\"$job\"},model)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "llamacpp_requests_processing{job=~\"$job\",model=~\"$model\"}",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Requests Processing and Requests Deferred",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "llamacpp_requests_processing{job=~\"$job\",model=~\"$model\"}",
     "legendFormat": "requests processing ({{model}})"
    },
    {
     "expr": "llamacpp_requests_deferred{job=~\"$job\",model=~\"$model\"}",
     "legendFormat": "requests deferred ({{model}})"
    }
   ]
  },
  {
   "title": "Requests in last 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(llamacpp_requests_processing{job=~\"$job\",model=~\"$model\"}[24h]))",
     "legendFormat": "Requests in last 24h"
    }
   ]
  },
  {
   "title": "Prompt processing speed, tokens/s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "llamacpp_prompt_tokens_seconds{job=~\"$job\",model=~\"$model\"}",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Processed tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "llamacpp_prompt_tokens_total{job=~\"$job\",model=~\"$model\"}",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Prompt processing time, s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "llamacpp_prompt_seconds_total{job=~\"$job\",model=~\"$model\"}",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Generation speed, tokens/s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "llamacpp_predicted_tokens_seconds{job=~\"$job\",model=~\"$model\"}",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Generated tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "llamacpp_tokens_predicted_total{job=~\"$job\",model=~\"$model\"}",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Generation time, s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "llamacpp_tokens_predicted_seconds_total{job=~\"$job\",model=~\"$model\"}",
     "legendFormat": "{{model}}"
    }
   ]
  },
  { "title": "Models", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Prompt processing speed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "llamacpp_prompt_tokens_seconds{job=~\"$job\",model=~\"$model\"}",
     "legendFormat": "t/s ({{model}})"
    }
   ]
  },
  {
   "title": "Processed tokens",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "llamacpp_prompt_tokens_total{job=~\"$job\",model=~\"$model\"}",
     "legendFormat": "tokens ({{model}})"
    }
   ]
  },
  {
   "title": "Prompt processing time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "llamacpp_prompt_seconds_total{job=~\"$job\",model=~\"$model\"}",
     "legendFormat": "s ({{model}})"
    }
   ]
  },
  {
   "title": "Generation speed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "llamacpp_predicted_tokens_seconds{job=~\"$job\",model=~\"$model\"}",
     "legendFormat": "t/s ({{model}})"
    }
   ]
  },
  {
   "title": "Generated tokens",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "llamacpp_tokens_predicted_total{job=~\"$job\",model=~\"$model\"}",
     "legendFormat": "tokens ({{model}})"
    }
   ]
  },
  {
   "title": "Generation time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "llamacpp_tokens_predicted_seconds_total{job=~\"$job\",model=~\"$model\"}",
     "legendFormat": "s ({{model}})"
    }
   ]
  },
  {
   "title": "Model: $model",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "repeat": "model",
   "collapsed": true,
   "panels": [
    {
     "title": "Prompt processing speed",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "llamacpp_prompt_tokens_seconds{job=~\"$job\",model=~\"$model\"}",
       "legendFormat": "t/s ({{model}})"
      }
     ]
    },
    {
     "title": "Processed tokens",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "llamacpp_prompt_tokens_total{job=~\"$job\",model=~\"$model\"}",
       "legendFormat": "tokens ({{model}})"
      }
     ]
    },
    {
     "title": "Prompt processing time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "llamacpp_prompt_seconds_total{job=~\"$job\",model=~\"$model\"}",
       "legendFormat": "s ({{model}})"
      }
     ]
    },
    {
     "title": "Generation speed",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "llamacpp_predicted_tokens_seconds{job=~\"$job\",model=~\"$model\"}",
       "legendFormat": "t/s ({{model}})"
      }
     ]
    },
    {
     "title": "Generated tokens",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "llamacpp_tokens_predicted_total{job=~\"$job\",model=~\"$model\"}",
       "legendFormat": "tokens ({{model}})"
      }
     ]
    },
    {
     "title": "Generation time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "llamacpp_tokens_predicted_seconds_total{job=~\"$job\",model=~\"$model\"}",
       "legendFormat": "s ({{model}})"
      }
     ]
    }
   ]
  },
  { "title": "llama.cpp functions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Total number of llama_decode() calls",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "llamacpp_n_decode_total{job=~\"$job\",model=~\"$model\"}",
     "legendFormat": "tokens ({{model}})"
    }
   ]
  },
  {
   "title": "Average number of busy slots per llama_decode() call",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "llamacpp_n_busy_slots_per_decode{job=~\"$job\",model=~\"$model\"}",
     "legendFormat": "tokens ({{model}})"
    }
   ]
  },
  {
   "title": "Largest observed n_past",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "llamacpp_n_past_max{job=~\"$job\",model=~\"$model\"}",
     "legendFormat": "tokens ({{model}})"
    }
   ]
  }
 ]
}