{
 "title": "GPU Monitoring (nvitop)",
 "tags": [
  "nvitop",
  "nvitop-exporter",
  "prometheus",
  "nvidia",
  "gpu",
  "gpu process",
  "gpu monitoring"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "query": { "query": "label_values(nvitop_info,job)" } },
   {
    "name": "hostname",
    "query": {
     "query": "label_values(nvitop_info{job=~\"$job\"},hostname)"
    }
   },
   {
    "name": "username",
    "query": {
     "query": "label_values(process_info_info{job=~\"$job\", hostname=~\"$hostname\"},username)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "host_cpu_percent_Percentage{job=~\"$job\", hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}} CPU"
    }
   ]
  },
  {
   "title": "Host Virtual Memory",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "host_virtual_memory_percent_Percentage{job=~\"$job\", hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}} MEM"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gpu_utilization_Percentage{job=~\"$job\", hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}} GPU {{index}}"
    }
   ]
  },
  {
   "title": "GPU Memory",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gpu_memory_percent_Percentage{job=~\"$job\", hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}} GPU {{index}}"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Number of GPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(group by(uuid) (process_gpu_memory_MiB{job=~\"$job\", hostname=~\"$hostname\", username=~\"$username\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(gpu_memory_total_MiB{job=~\"$job\", hostname=~\"$hostname\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Running GPU Processes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by(hostname, index) (process_gpu_memory_MiB{job=~\"$job\", hostname=~\"$hostname\", username=~\"$username\"})",
     "legendFormat": "{{hostname}} GPU {{index}}"
    }
   ]
  },
  {
   "title": "Number of Running GPU Processes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by(hostname) (count by(hostname, pid) (process_info_info{job=~\"$job\", hostname=~\"$hostname\", username=~\"$username\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Processes",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "process_cpu_percent_Percentage{job=~\"$job\", hostname=~\"$hostname\", username=~\"$username\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_rss_memory_MiB{job=~\"$job\", hostname=~\"$hostname\", username=~\"$username\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_gpu_memory_MiB{job=~\"$job\", hostname=~\"$hostname\", username=~\"$username\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_gpu_sm_utilization_Percentage{job=~\"$job\", hostname=~\"$hostname\", username=~\"$username\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_gpu_memory_utilization_Percentage{job=~\"$job\", hostname=~\"$hostname\", username=~\"$username\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_gpu_encoder_utilization_Percentage{job=~\"$job\", hostname=~\"$hostname\", username=~\"$username\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_gpu_decoder_utilization_Percentage{job=~\"$job\", hostname=~\"$hostname\", username=~\"$username\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_running_time_Second{job=~\"$job\", hostname=~\"$hostname\", username=~\"$username\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_info_info{job=~\"$job\", hostname=~\"$hostname\", username=~\"$username\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "host_virtual_memory_total_MiB{job=~\"$job\", hostname=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu_memory_total_MiB{job=~\"$job\", hostname!~\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "host_cpu_percent_Percentage{job=~\"$job\", hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "CPU Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "host_load_average_1m_Percentage{job=~\"$job\", hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}} (1m)"
    },
    {
     "expr": "host_load_average_5m_Percentage{job=~\"$job\", hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}} (5m)"
    },
    {
     "expr": "host_load_average_15m_Percentage{job=~\"$job\", hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}} (15m)"
    }
   ]
  },
  {
   "title": "Host Virtual Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "host_virtual_memory_used_MiB{job=~\"$job\", hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Host Swap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "host_swap_memory_used_MiB{job=~\"$job\", hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "System I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Host Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "sum by(hostname) (rate(host_net_io_rx_data_MiB{job=~\"$job\", hostname=~\"$hostname\"}[$__rate_interval]))",
     "legendFormat": "{{hostname}} RX"
    },
    {
     "expr": "sum by(hostname) (rate(host_net_io_tx_data_MiB{job=~\"$job\", hostname=~\"$hostname\"}[$__rate_interval]))",
     "legendFormat": "{{hostname}} TX"
    }
   ]
  },
  {
   "title": "Host Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "sum by(hostname) (rate(host_disk_io_read_data_MiB{hostname=~\"$hostname\"}[$__rate_interval]))",
     "legendFormat": "{{hostname}} Read"
    },
    {
     "expr": "sum by(hostname) (rate(host_disk_io_write_data_MiB{hostname=~\"$hostname\"}[$__rate_interval]))",
     "legendFormat": "{{hostname}} Write"
    }
   ]
  },
  { "title": "Device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gpu_utilization_Percentage{job=~\"$job\", hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}} GPU {{index}}"
    }
   ]
  },
  {
   "title": "GPU Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "gpu_memory_used_MiB{job=~\"$job\", hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}} GPU {{index}}"
    }
   ]
  },
  {
   "title": "GPU PCIe RX Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "gpu_pcie_rx_throughput_MiBps{job=~\"$job\", hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}} GPU {{index}}"
    }
   ]
  },
  {
   "title": "GPU PCIe TX Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "gpu_pcie_tx_throughput_MiBps{job=~\"$job\", hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}} GPU {{index}}"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "gpu_power_usage_W{job=~\"$job\", hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}} GPU {{index}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "gpu_temperature_C{job=~\"$job\", hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}} GPU {{index}}"
    }
   ]
  },
  {
   "title": "NVLink",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU NVLink RX Throughput",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "expr": "gpu_nvlink_total_rx_throughput_MiBps{job=~\"$job\", hostname=~\"$hostname\"}",
       "legendFormat": "{{hostname}} GPU {{index}}"
      }
     ]
    },
    {
     "title": "GPU NVLink TX Throughput",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "expr": "gpu_nvlink_total_tx_throughput_MiBps{job=~\"$job\", hostname=~\"$hostname\"}",
       "legendFormat": "{{hostname}} GPU {{index}}"
      }
     ]
    }
   ]
  }
 ]
}